package com.gedavocat.security;

import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;

import java.io.IOException;
import java.security.SecureRandom;
import java.util.Base64;

/**
 * Generates a per-request CSP nonce and sets the Content-Security-Policy header.
 * Templates access the nonce via ${cspNonce} to add nonce="..." to inline scripts/styles.
 *
 * script-src: nonce strict + 'unsafe-hashes' avec sha256 de tous les attributs onclick/onchange/etc.
 *   — 'unsafe-hashes' autorise les event handlers inline (onclick="...") dont le sha256 est listé.
 *   — Les <script nonce="..."> blocks sont protégés par le nonce per-request.
 * style-src: 'unsafe-inline' autorisé (635 inline styles dans les templates — CSS injection
 *   ne permet pas d'exécuter du code).
 *
 * Pour régénérer les hashes après ajout de nouveaux event handlers :
 *   node compute-csp-hashes.js (à la racine du projet)
 */
@Component
@Order(1)
public class CspNonceFilter extends OncePerRequestFilter {

    private static final SecureRandom RANDOM = new SecureRandom();
    private static final int NONCE_BYTES = 16;

    // CDN origins
    private static final String CDN_JSDELIVR = "https://cdn.jsdelivr.net";
    private static final String CDN_CDNJS = "https://cdnjs.cloudflare.com";
    private static final String GOOGLE_FONTS_CSS = "https://fonts.googleapis.com";
    private static final String GOOGLE_FONTS_FILES = "https://fonts.gstatic.com";

    // sha256 hashes of all inline event handler values (onclick="...", onchange="...", etc.)
    // Generated by: node compute-csp-hashes.js
    private static final String EVENT_HANDLER_HASHES =
        "'sha256-erB8A1sGOLM/CyVzJs5QoutJcNAvMa+UISZ5fQwDQY8=' " +
        "'sha256-uPdNwnbiOvEac0vEP+HJYGme1U6DY0ifSwJW2ZevJck=' " +
        "'sha256-xqnb9FR289sSK2osepMkLqnKiPmG5Tn0CoaKUrJ8vB8=' " +
        "'sha256-Jj8+rJwrYROQyWJgBEAOFu7HUI2e8ZVy8uiSFh1Lpdw=' " +
        "'sha256-bVr5ZLAbDUdXuGBIZH48uSEGzXEUyzPi28zQL5ojR3s=' " +
        "'sha256-gORb52qw9HwW0xw77AOuuSJM/MtdS884tR45Qs2Yx3k=' " +
        "'sha256-0/OwNZQ3/TzYjocKq1+MZ7c+Vi+vRLiF+puWneZiUPI=' " +
        "'sha256-iRoHbR7zWVEu0Odg/T7HI/fYp2ywSIXKKTPgyN+GEfs=' " +
        "'sha256-4zHUG3MtB3a5U/lAmlv1QqfymiPi/I8ACakIRd9h9SQ=' " +
        "'sha256-Tvc92zrAZJw+c8Q6bLVEwISmf/7pCbq+5LzxSnlA80o=' " +
        "'sha256-4RyzQzw3sUoNvupFPwiOmvCUpYsSWkXi+vKPDcFOLC8=' " +
        "'sha256-/hZ4vlC652dczene00410GJKzOe/9VBoCzOLoVqiL48=' " +
        "'sha256-xWYI918AgGEmg23L+IRAqbK+suUpCShyTa46ZCtTKrM=' " +
        "'sha256-X41Eo+Qa4iSnPy4ESIxX7R4Eq1NlZKhDAS5kgS51I8g=' " +
        "'sha256-CMyXbRlK+byg7embJUynhI5iYmfuIi4Chfo3mgqTDc4=' " +
        "'sha256-3PvFHYATB04OYs2tV0f3T31uDt0hjWdiv6ToMNejUBk=' " +
        "'sha256-jHF5hTIlMDyGZRAsNK0HO/WFYrwPvI2I1q0o1xKKB6I=' " +
        "'sha256-pn5Jlm6aPkRoc1DYGzYYsg1gL6jlQfxI7YIilpD9IpQ=' " +
        "'sha256-GyL92nE+Ld+AVAm++UGAHP7I4OvlxtqdhXRtrjUj8Zo=' " +
        "'sha256-M6gB0hINCypeSK/2vuk/wHrKj/t0RXK+KiVAceQ1Jts=' " +
        "'sha256-LgDAOY2n53hBxXxSd9XCiKllvmFlj2sRSzDKSuNGrR4=' " +
        "'sha256-xMBqeVGlnYp2y5fMqYszVK9Xjjz6XyjazYEi9BdC2+g=' " +
        "'sha256-WFv3L03QbHiYvG4i6nLzfiAZtXDCDviBiEthVRSjguk=' " +
        "'sha256-EH/23HNPBbpoGH5T4z0Q2ILLgh7Tu9ECQbnDH2veNPA=' " +
        "'sha256-gGib3APOyIi51b2r0tejVoc1s196d9R3yg4lw/WUeeU=' " +
        "'sha256-74MsHEjSsWhDZjfwqEiPQhf7UpkyV5Vq/UwMdC2GiQ0=' " +
        "'sha256-zANpl9xci7JAPmHkX9o6UPAYEHVsK1qqGoE/Dqi6Z8M=' " +
        "'sha256-b+nA+mCMv3ZG0LViDtsKl2XwOGu4xXiKExONAK53vvo=' " +
        "'sha256-4eC5LLWm896ii/0Ce6iayFDCWUXulGA0w8aTJ24Sai4=' " +
        "'sha256-8BJS8Pz5vTmCLfJlJa3lHw8N2SxEKGpUrBOEx2h8dZY=' " +
        "'sha256-9Bo3a8j2vZkjTH1mHcVLDaesAqSwmncOImzdxnCgqu0=' " +
        "'sha256-VnsbdN0nE/b0rcWb69QZltYV4TjMHrQ20wnzubdO+Vc=' " +
        "'sha256-CgQgT/IsLkXkpRee3g/w6z1s2hoXE22oNdzXBKVH2PQ=' " +
        "'sha256-/KbKEZV9+Hu1L3iScc33RVNtCr6H2oEGLIL8qYGdS+c=' " +
        "'sha256-WzLCeULQgMPGN5KHTcOnB9HUcuhRmsIQaWPUCxLWAIA=' " +
        "'sha256-qKrH/Zx7JlcuxKvzb10se0gzSI1wQ+IVh+UNlz6kNMw=' " +
        "'sha256-H0yHmSjTYBfzspDyztoFCv/xGRkztRXVAp9Eo/MVSF0=' " +
        "'sha256-GuNAr335NuyDip/UszIk7k/kyA0HV3RavBI1v54Vcv4=' " +
        "'sha256-xOiwVSvk8LNlnu1lMqulskzw/xbuhu2QhIwzhO3g+rg=' " +
        "'sha256-UZA1UeZ83i9QwYrI0Rk1GH9Qx6ejVhfp65eZON7bqwE=' " +
        "'sha256-b/ARtiMJh5dxTD7eWUErSloBNCuauJtMCwgB7gxmCKA=' " +
        "'sha256-jRbrfhwML0G7dvj3lffgzPE5cT8n52RphnlGqe4ibXI=' " +
        "'sha256-bLTVchILfiMSBWTAhmNNGmWgRC8QiMriZ/5oA00+yIQ=' " +
        "'sha256-wlEqVPICWkUskwmsDFKaPu9ckXUTh546YJJjRqKFJT4=' " +
        "'sha256-kvDsQ2glvOwzdM77KBWX+7xp/5ufE4qbNshM13nD/rk=' " +
        "'sha256-F9XMb0qDh0VRxeEzaN288kLdNht/Yb2pGMyjksoGjyw=' " +
        "'sha256-VdDijwD8iDLEJI2QJFNt1pkypo66Q5r8GWS2qxURPwM=' " +
        "'sha256-HH+yC4BMb6GymbvabuEPE9BLircPj+gATKY5zBhoClA=' " +
        "'sha256-tfUwzczqQHhoesmlvynsnZ/2F3dh/9CMOWGQydM8CZk=' " +
        "'sha256-xnCcAoNyyylevwRSuotYkOGP9v88YCDbIzmvgL3mhjw=' " +
        "'sha256-TF4oaEuloySfF/dXHYwq+T5ciyjUcgk+tZG86T03YpE=' " +
        "'sha256-bEPo34EO4XFNEHntmCcADIrHXBvDTuT6V6KrkWIlRY0=' " +
        "'sha256-rREGifqmem3Fe6WD8TqogJgJnOEglzIfGpMis4Ypm30=' " +
        "'sha256-dYSD1tum71az8E3eeV4EbOoDnxXz+dUQ3jIM7XnSFi8=' " +
        "'sha256-Q6zNxcAa/d7Sw0efemEqSkmVjAIRnmp726RINj2gLFU=' " +
        "'sha256-z/BlA6v+y78y8M6/Ln5RABJiJUesh+r2dVFzhqVuJjk=' " +
        "'sha256-w6M7t5/qR/B2nxMxWhW9W0LNMixkSRWPkQfEAUs/c+A=' " +
        "'sha256-FBgS1V1mJ5mDqr/KGIvKJ56A6siMZBVBs19sw/Gs5uA=' " +
        "'sha256-jmth4Ubkdt2j2IeRSk1e/HbgLTeHE2iLwxzksx7iThY=' " +
        "'sha256-Vl/EmQ8YTwbfm4WOYr5met4WCCxIbQk4mgIFF9oE80A=' " +
        "'sha256-RV9pZEENhiXLw0C+1+wsN3EzxiXzNiDWDcTUG6XNltA=' " +
        "'sha256-n4oalB+y3N79NJpArpmcczLoo+6TFwqMgUrYajMKXmA=' " +
        "'sha256-kT64kcvFD5WYBWQPT0bgnA5Zl5PnKtHPE+XmPl3xiuw=' " +
        "'sha256-osjxnKEPL/pQJbFk1dKsF7PYFmTyMWGmVSiL9inhxJY=' " +
        "'sha256-biFQTroSCI3Z5BmsMGyEE2jFZdwjjG1Oe7JLytgH6jM=' " +
        "'sha256-FxJeAOk9K1DkcC/Esj5bTY5w4qil8woFhG1ropkxjWU=' " +
        "'sha256-Ktbl1TtPCpRWUHL81InKp91iFTRmeCkc+GhwtnixcyI=' " +
        "'sha256-SvPFfvH4CWRlMqJd+Dkt6VSjbiqlAYqMWQHFJHXn+aA=' " +
        "'sha256-q0GphC6xMoSdBOJqTkHN3eFsZvYuQ7bA++FHSiXN6B8=' " +
        "'sha256-yNNmWb4CnJPOrQ4cKasi6RnEV7skZ8l1MNhaig6/4hE=' " +
        "'sha256-fBlaiEAdwq5C6q7RhzdOPPHHIMP3DLeE1KzHAvSrckY=' " +
        "'sha256-FovXx8kIPFB1+Mk3OGuYW9BACJwmuXwj807BjR89nVw=' " +
        "'sha256-TeU1wTEnoCgmCfXcjcy02kB7CGuFOWSPQencusxD/i4=' " +
        "'sha256-oobUj9EcSDX2Cp3935qErt2DLoZ4ctI8YQYt32ZTk20=' " +
        "'sha256-ypx5/tuejr+AKLgMAdy2pjEBeWtm3/W7m7iGoZF87tc=' " +
        "'sha256-XkDSjG+c+AmQiHCnOOFNUHOWuf/i8NcVGS9vRWJhwCs=' " +
        "'sha256-WSIriWT1PEdJqRK+3IBqMnKx0WfxaO6/1Pyr47g1bgw=' " +
        "'sha256-ey571AhXEzUyTRqzKAI4tLv8/Sx/+I5oXCzlOhX+4UY=' " +
        "'sha256-YK4l+MI+vFfNkOrOuPZ/2Pblear/pqVdoApMgrMooik=' " +
        "'sha256-i6mc/EckCMf65C39ZY69JwcrmmyMtc3Nsmja4Q5N/28=' " +
        "'sha256-pcfR3TUS8UZgeKKl4z0xDkkBNmp4XxjJntXZKaJJGCs=' " +
        "'sha256-4TpZ3Tx5SLybDXPQaSHGuP1RU4D+pzck+02JLVY61BY=' " +
        "'sha256-MguIPR6qNR8D3B+eAlK+bIRTZe8t3wkOY4B/56Me9FU='";

    @Override
    protected void doFilterInternal(HttpServletRequest request,
                                    HttpServletResponse response,
                                    FilterChain filterChain)
            throws ServletException, IOException {

        byte[] nonceBytes = new byte[NONCE_BYTES];
        RANDOM.nextBytes(nonceBytes);
        String nonce = Base64.getEncoder().encodeToString(nonceBytes);

        // Expose nonce to Thymeleaf templates as ${cspNonce}
        request.setAttribute("cspNonce", nonce);

        // Build CSP with per-request nonce
        // script-src: nonce strict pour les <script> blocks + 'unsafe-hashes' + sha256 des event handlers
        //   inline (onclick/onchange/onsubmit etc.). 'unsafe-hashes' autorise UNIQUEMENT les handlers
        //   dont le sha256 est listé — pas d'exécution arbitraire.
        // style-src: 'unsafe-inline' autorisé (635 inline styles — CSS ne peut pas exécuter du code).
        String csp = "default-src 'self'; " +
                "script-src 'self' 'nonce-" + nonce + "' 'unsafe-hashes' " + EVENT_HANDLER_HASHES +
                " https://js.stripe.com " + CDN_JSDELIVR + "; " +
                "style-src 'self' 'unsafe-inline' " + CDN_JSDELIVR + " " + CDN_CDNJS + " " + GOOGLE_FONTS_CSS + "; " +
                "font-src 'self' data: " + CDN_CDNJS + " " + GOOGLE_FONTS_FILES + "; " +
                "img-src 'self' data:; " +
                "connect-src 'self' https://api.stripe.com https://api.payplug.com " + CDN_JSDELIVR + "; " +
                "frame-src 'self' https://js.stripe.com https://hooks.stripe.com; " +
                "object-src 'none'; " +
                "base-uri 'self'; " +
                "frame-ancestors 'self'";

        response.setHeader("Content-Security-Policy", csp);

        filterChain.doFilter(request, response);
    }
}
