INSERT INTO barreaux_france (barreau, region, ville_siege, cour_appel, tribunal_judiciaire, actif) VALUES
('Agen', 'Nouvelle-Aquitaine', 'Agen', 'Agen', 'Agen', 1),
('Aix-en-Provence', 'Provence-Alpes-Côte d''Azur', 'Aix-en-Provence', 'Aix-en-Provence', 'Aix-en-Provence', 1),
('Ajaccio', 'Corse', 'Ajaccio', 'Bastia', 'Ajaccio', 1),
('Albertville', 'Auvergne-Rhône-Alpes', 'Albertville', 'Chambéry', 'Albertville', 1),
('Albi', 'Occitanie', 'Albi', 'Toulouse', 'Albi', 1),
('Alençon', 'Normandie', 'Alençon', 'Caen', 'Alençon', 1),
('Amiens', 'Hauts-de-France', 'Amiens', 'Amiens', 'Amiens', 1),
('Angers', 'Pays de la Loire', 'Angers', 'Angers', 'Angers', 1),
('Angoulême', 'Nouvelle-Aquitaine', 'Angoulême', 'Bordeaux', 'Angoulême', 1),
('Annecy', 'Auvergne-Rhône-Alpes', 'Annecy', 'Chambéry', 'Annecy', 1),
('Argentan', 'Normandie', 'Argentan', 'Caen', 'Argentan', 1),
('Aurillac', 'Auvergne-Rhône-Alpes', 'Aurillac', 'Riom', 'Aurillac', 1),
('Auxerre', 'Bourgogne-Franche-Comté', 'Auxerre', 'Paris', 'Auxerre', 1),
('Avesnes-sur-Helpe', 'Hauts-de-France', 'Avesnes-sur-Helpe', 'Douai', 'Avesnes-sur-Helpe', 1),
('Avignon', 'Provence-Alpes-Côte d''Azur', 'Avignon', 'Nîmes', 'Avignon', 1),
('Bar-le-Duc', 'Grand Est', 'Bar-le-Duc', 'Nancy', 'Bar-le-Duc', 1),
('Bastia', 'Corse', 'Bastia', 'Bastia', 'Bastia', 1),
('Bayonne', 'Nouvelle-Aquitaine', 'Bayonne', 'Pau', 'Bayonne', 1),
('Beauvais', 'Hauts-de-France', 'Beauvais', 'Amiens', 'Beauvais', 1),
('Belfort', 'Bourgogne-Franche-Comté', 'Belfort', 'Besançon', 'Belfort', 1),
('Bergerac', 'Nouvelle-Aquitaine', 'Bergerac', 'Bordeaux', 'Bergerac', 1),
('Besançon', 'Bourgogne-Franche-Comté', 'Besançon', 'Besançon', 'Besançon', 1),
('Béthune', 'Hauts-de-France', 'Béthune', 'Douai', 'Béthune', 1),
('Béziers', 'Occitanie', 'Béziers', 'Montpellier', 'Béziers', 1),
('Blois', 'Centre-Val de Loire', 'Blois', 'Orléans', 'Blois', 1),
('Bobigny', 'Île-de-France', 'Bobigny', 'Paris', 'Bobigny', 1),
('Bordeaux', 'Nouvelle-Aquitaine', 'Bordeaux', 'Bordeaux', 'Bordeaux', 1),
('Boulogne-sur-Mer', 'Hauts-de-France', 'Boulogne-sur-Mer', 'Douai', 'Boulogne-sur-Mer', 1),
('Bourg-en-Bresse', 'Auvergne-Rhône-Alpes', 'Bourg-en-Bresse', 'Lyon', 'Bourg-en-Bresse', 1),
('Bourges', 'Centre-Val de Loire', 'Bourges', 'Bourges', 'Bourges', 1),
('Brest', 'Bretagne', 'Brest', 'Rennes', 'Brest', 1),
('Briey', 'Grand Est', 'Briey', 'Nancy', 'Briey', 1),
('Brive-la-Gaillarde', 'Nouvelle-Aquitaine', 'Brive-la-Gaillarde', 'Limoges', 'Brive-la-Gaillarde', 1),
('Caen', 'Normandie', 'Caen', 'Caen', 'Caen', 1),
('Cahors', 'Occitanie', 'Cahors', 'Agen', 'Cahors', 1),
('Cambrai', 'Hauts-de-France', 'Cambrai', 'Douai', 'Cambrai', 1),
('Carcassonne', 'Occitanie', 'Carcassonne', 'Montpellier', 'Carcassonne', 1),
('Carpentras', 'Provence-Alpes-Côte d''Azur', 'Carpentras', 'Nîmes', 'Carpentras', 1),
('Castres', 'Occitanie', 'Castres', 'Toulouse', 'Castres', 1),
('Chalon-sur-Saône', 'Bourgogne-Franche-Comté', 'Chalon-sur-Saône', 'Dijon', 'Chalon-sur-Saône', 1),
('Châlons-en-Champagne', 'Grand Est', 'Châlons-en-Champagne', 'Reims', 'Châlons-en-Champagne', 1),
('Chambéry', 'Auvergne-Rhône-Alpes', 'Chambéry', 'Chambéry', 'Chambéry', 1),
('Chartres', 'Centre-Val de Loire', 'Chartres', 'Versailles', 'Chartres', 1),
('Chaumont', 'Grand Est', 'Chaumont', 'Dijon', 'Chaumont', 1),
('Cherbourg-en-Cotentin', 'Normandie', 'Cherbourg-en-Cotentin', 'Caen', 'Cherbourg-en-Cotentin', 1),
('Clermont-Ferrand', 'Auvergne-Rhône-Alpes', 'Clermont-Ferrand', 'Riom', 'Clermont-Ferrand', 1),
('Colmar', 'Grand Est', 'Colmar', 'Colmar', 'Colmar', 1),
('Compiègne', 'Hauts-de-France', 'Compiègne', 'Amiens', 'Compiègne', 1),
('Coutances', 'Normandie', 'Coutances', 'Caen', 'Coutances', 1),
('Créteil', 'Île-de-France', 'Créteil', 'Paris', 'Créteil', 1),
('Cusset-Vichy', 'Auvergne-Rhône-Alpes', 'Cusset', 'Riom', 'Cusset', 1),
('Dax', 'Nouvelle-Aquitaine', 'Dax', 'Pau', 'Dax', 1),
('Dieppe', 'Normandie', 'Dieppe', 'Rouen', 'Dieppe', 1),
('Dijon', 'Bourgogne-Franche-Comté', 'Dijon', 'Dijon', 'Dijon', 1),
('Douai', 'Hauts-de-France', 'Douai', 'Douai', 'Douai', 1),
('Draguignan', 'Provence-Alpes-Côte d''Azur', 'Draguignan', 'Aix-en-Provence', 'Draguignan', 1),
('Dunkerque', 'Hauts-de-France', 'Dunkerque', 'Douai', 'Dunkerque', 1),
('Épinal', 'Grand Est', 'Épinal', 'Nancy', 'Épinal', 1),
('Essonne', 'Île-de-France', 'Évry', 'Paris', 'Évry', 1),
('Évreux', 'Normandie', 'Évreux', 'Rouen', 'Évreux', 1),
('Foix', 'Occitanie', 'Foix', 'Toulouse', 'Foix', 1),
('Fontainebleau', 'Île-de-France', 'Fontainebleau', 'Paris', 'Fontainebleau', 1),
('Gap', 'Provence-Alpes-Côte d''Azur', 'Gap', 'Grenoble', 'Gap', 1),
('Grasse', 'Provence-Alpes-Côte d''Azur', 'Grasse', 'Aix-en-Provence', 'Grasse', 1),
('Grenoble', 'Auvergne-Rhône-Alpes', 'Grenoble', 'Grenoble', 'Grenoble', 1),
('Guéret', 'Nouvelle-Aquitaine', 'Guéret', 'Limoges', 'Guéret', 1),
('Hauts-de-Seine', 'Île-de-France', 'Nanterre', 'Versailles', 'Nanterre', 1),
('La Rochelle', 'Nouvelle-Aquitaine', 'La Rochelle', 'Poitiers', 'La Rochelle', 1),
('La Roche-sur-Yon', 'Pays de la Loire', 'La Roche-sur-Yon', 'Poitiers', 'La Roche-sur-Yon', 1),
('Laon', 'Hauts-de-France', 'Laon', 'Amiens', 'Laon', 1),
('Laval', 'Pays de la Loire', 'Laval', 'Angers', 'Laval', 1),
('Le Havre', 'Normandie', 'Le Havre', 'Rouen', 'Le Havre', 1),
('Le Mans', 'Pays de la Loire', 'Le Mans', 'Angers', 'Le Mans', 1),
('Le Puy-en-Velay', 'Auvergne-Rhône-Alpes', 'Le Puy-en-Velay', 'Riom', 'Le Puy-en-Velay', 1),
('Libourne', 'Nouvelle-Aquitaine', 'Libourne', 'Bordeaux', 'Libourne', 1),
('Lille', 'Hauts-de-France', 'Lille', 'Douai', 'Lille', 1),
('Limoges', 'Nouvelle-Aquitaine', 'Limoges', 'Limoges', 'Limoges', 1),
('Lisieux', 'Normandie', 'Lisieux', 'Caen', 'Lisieux', 1),
('Lons-le-Saunier', 'Bourgogne-Franche-Comté', 'Lons-le-Saunier', 'Besançon', 'Lons-le-Saunier', 1),
('Lorient', 'Bretagne', 'Lorient', 'Rennes', 'Lorient', 1),
('Lyon', 'Auvergne-Rhône-Alpes', 'Lyon', 'Lyon', 'Lyon', 1),
('Mâcon', 'Bourgogne-Franche-Comté', 'Mâcon', 'Dijon', 'Mâcon', 1),
('Marseille', 'Provence-Alpes-Côte d''Azur', 'Marseille', 'Aix-en-Provence', 'Marseille', 1),
('Meaux', 'Île-de-France', 'Meaux', 'Paris', 'Meaux', 1),
('Melun', 'Île-de-France', 'Melun', 'Paris', 'Melun', 1),
('Metz', 'Grand Est', 'Metz', 'Metz', 'Metz', 1),
('Montauban', 'Occitanie', 'Montauban', 'Toulouse', 'Montauban', 1),
('Montbéliard', 'Bourgogne-Franche-Comté', 'Montbéliard', 'Besançon', 'Montbéliard', 1),
('Mont-de-Marsan', 'Nouvelle-Aquitaine', 'Mont-de-Marsan', 'Pau', 'Mont-de-Marsan', 1),
('Montluçon', 'Auvergne-Rhône-Alpes', 'Montluçon', 'Riom', 'Montluçon', 1),
('Montpellier', 'Occitanie', 'Montpellier', 'Montpellier', 'Montpellier', 1),
('Morlaix', 'Bretagne', 'Morlaix', 'Rennes', 'Morlaix', 1),
('Moulins', 'Auvergne-Rhône-Alpes', 'Moulins', 'Riom', 'Moulins', 1),
('Mulhouse', 'Grand Est', 'Mulhouse', 'Colmar', 'Mulhouse', 1),
('Nancy', 'Grand Est', 'Nancy', 'Nancy', 'Nancy', 1),
('Nantes', 'Pays de la Loire', 'Nantes', 'Rennes', 'Nantes', 1),
('Narbonne', 'Occitanie', 'Narbonne', 'Montpellier', 'Narbonne', 1),
('Nevers', 'Bourgogne-Franche-Comté', 'Nevers', 'Bourges', 'Nevers', 1),
('Nice', 'Provence-Alpes-Côte d''Azur', 'Nice', 'Aix-en-Provence', 'Nice', 1),
('Nîmes', 'Occitanie', 'Nîmes', 'Nîmes', 'Nîmes', 1),
('Niort', 'Nouvelle-Aquitaine', 'Niort', 'Poitiers', 'Niort', 1),
('Orléans', 'Centre-Val de Loire', 'Orléans', 'Orléans', 'Orléans', 1),
('Paris', 'Île-de-France', 'Paris', 'Paris', 'Paris', 1),
('Pau', 'Nouvelle-Aquitaine', 'Pau', 'Pau', 'Pau', 1),
('Périgueux', 'Nouvelle-Aquitaine', 'Périgueux', 'Bordeaux', 'Périgueux', 1),
('Perpignan', 'Occitanie', 'Perpignan', 'Montpellier', 'Perpignan', 1),
('Pointe-à-Pitre', 'Guadeloupe', 'Pointe-à-Pitre', 'Basse-Terre', 'Pointe-à-Pitre', 1),
('Poitiers', 'Nouvelle-Aquitaine', 'Poitiers', 'Poitiers', 'Poitiers', 1),
('Pontoise', 'Île-de-France', 'Pontoise', 'Versailles', 'Pontoise', 1),
('Quimper', 'Bretagne', 'Quimper', 'Rennes', 'Quimper', 1),
('Reims', 'Grand Est', 'Reims', 'Reims', 'Reims', 1),
('Rennes', 'Bretagne', 'Rennes', 'Rennes', 'Rennes', 1),
('Roanne', 'Auvergne-Rhône-Alpes', 'Roanne', 'Lyon', 'Roanne', 1),
('Rodez', 'Occitanie', 'Rodez', 'Montpellier', 'Rodez', 1),
('Rouen', 'Normandie', 'Rouen', 'Rouen', 'Rouen', 1),
('Saintes', 'Nouvelle-Aquitaine', 'Saintes', 'Poitiers', 'Saintes', 1),
('Saint-Brieuc', 'Bretagne', 'Saint-Brieuc', 'Rennes', 'Saint-Brieuc', 1),
('Saint-Denis de la Réunion', 'La Réunion', 'Saint-Denis', 'Saint-Denis', 'Saint-Denis', 1),
('Saint-Étienne', 'Auvergne-Rhône-Alpes', 'Saint-Étienne', 'Lyon', 'Saint-Étienne', 1),
('Saint-Malo', 'Bretagne', 'Saint-Malo', 'Rennes', 'Saint-Malo', 1),
('Saint-Nazaire', 'Pays de la Loire', 'Saint-Nazaire', 'Rennes', 'Saint-Nazaire', 1),
('Saint-Omer', 'Hauts-de-France', 'Saint-Omer', 'Douai', 'Saint-Omer', 1),
('Saint-Pierre de la Martinique', 'Martinique', 'Fort-de-France', 'Fort-de-France', 'Fort-de-France', 1),
('Saint-Quentin', 'Hauts-de-France', 'Saint-Quentin', 'Amiens', 'Saint-Quentin', 1),
('Sarreguemines', 'Grand Est', 'Sarreguemines', 'Metz', 'Sarreguemines', 1),
('Saverne', 'Grand Est', 'Saverne', 'Colmar', 'Saverne', 1),
('Sedan', 'Grand Est', 'Sedan', 'Reims', 'Sedan', 1),
('Senlis', 'Hauts-de-France', 'Senlis', 'Amiens', 'Senlis', 1),
('Sens', 'Bourgogne-Franche-Comté', 'Sens', 'Paris', 'Sens', 1),
('Soissons', 'Hauts-de-France', 'Soissons', 'Amiens', 'Soissons', 1),
('Strasbourg', 'Grand Est', 'Strasbourg', 'Colmar', 'Strasbourg', 1),
('Tarbes', 'Occitanie', 'Tarbes', 'Pau', 'Tarbes', 1),
('Thionville', 'Grand Est', 'Thionville', 'Metz', 'Thionville', 1),
('Thonon-les-Bains', 'Auvergne-Rhône-Alpes', 'Thonon-les-Bains', 'Chambéry', 'Thonon-les-Bains', 1),
('Toulon', 'Provence-Alpes-Côte d''Azur', 'Toulon', 'Aix-en-Provence', 'Toulon', 1),
('Toulouse', 'Occitanie', 'Toulouse', 'Toulouse', 'Toulouse', 1),
('Tours', 'Centre-Val de Loire', 'Tours', 'Orléans', 'Tours', 1),
('Troyes', 'Grand Est', 'Troyes', 'Reims', 'Troyes', 1),
('Tulle', 'Nouvelle-Aquitaine', 'Tulle', 'Limoges', 'Tulle', 1),
('Val-de-Briey', 'Grand Est', 'Val-de-Briey', 'Nancy', 'Val-de-Briey', 1),
('Valenciennes', 'Hauts-de-France', 'Valenciennes', 'Douai', 'Valenciennes', 1),
('Vannes', 'Bretagne', 'Vannes', 'Rennes', 'Vannes', 1),
('Verdun', 'Grand Est', 'Verdun', 'Nancy', 'Verdun', 1),
('Versailles', 'Île-de-France', 'Versailles', 'Versailles', 'Versailles', 1),
('Vesoul', 'Bourgogne-Franche-Comté', 'Vesoul', 'Besançon', 'Vesoul', 1),
('Vienne', 'Auvergne-Rhône-Alpes', 'Vienne', 'Grenoble', 'Vienne', 1),
('Villefranche-sur-Saône', 'Auvergne-Rhône-Alpes', 'Villefranche-sur-Saône', 'Lyon', 'Villefranche-sur-Saône', 1),
('Cayenne', 'Guyane', 'Cayenne', 'Cayenne', 'Cayenne', 1),
('Mamoudzou', 'Mayotte', 'Mamoudzou', 'Saint-Denis', 'Mamoudzou', 1),
('Nouméa', 'Nouvelle-Calédonie', 'Nouméa', 'Nouméa', 'Nouméa', 1),
('Papeete', 'Polynésie française', 'Papeete', 'Papeete', 'Papeete', 1);
