SET NAMES utf8mb4;
INSERT INTO barreaux_france (barreau, region, ville_siege, cour_appel, tribunal_judiciaire, actif) VALUES
('Agen', 'Nouvelle-Aquitaine', 'Agen', 'Agen', 'Agen', 1),
('Aix-en-Provence', 'Provence-Alpes-CÃ´te d''Azur', 'Aix-en-Provence', 'Aix-en-Provence', 'Aix-en-Provence', 1),
('Ajaccio', 'Corse', 'Ajaccio', 'Bastia', 'Ajaccio', 1),
('Albertville', 'Auvergne-RhÃ´ne-Alpes', 'Albertville', 'ChambÃ©ry', 'Albertville', 1),
('Albi', 'Occitanie', 'Albi', 'Toulouse', 'Albi', 1),
('AlenÃ§on', 'Normandie', 'AlenÃ§on', 'Caen', 'AlenÃ§on', 1),
('Amiens', 'Hauts-de-France', 'Amiens', 'Amiens', 'Amiens', 1),
('Angers', 'Pays de la Loire', 'Angers', 'Angers', 'Angers', 1),
('AngoulÃªme', 'Nouvelle-Aquitaine', 'AngoulÃªme', 'Bordeaux', 'AngoulÃªme', 1),
('Annecy', 'Auvergne-RhÃ´ne-Alpes', 'Annecy', 'ChambÃ©ry', 'Annecy', 1),
('Argentan', 'Normandie', 'Argentan', 'Caen', 'Argentan', 1),
('Aurillac', 'Auvergne-RhÃ´ne-Alpes', 'Aurillac', 'Riom', 'Aurillac', 1),
('Auxerre', 'Bourgogne-Franche-ComtÃ©', 'Auxerre', 'Paris', 'Auxerre', 1),
('Avesnes-sur-Helpe', 'Hauts-de-France', 'Avesnes-sur-Helpe', 'Douai', 'Avesnes-sur-Helpe', 1),
('Avignon', 'Provence-Alpes-CÃ´te d''Azur', 'Avignon', 'NÃ®mes', 'Avignon', 1),
('Bar-le-Duc', 'Grand Est', 'Bar-le-Duc', 'Nancy', 'Bar-le-Duc', 1),
('Bastia', 'Corse', 'Bastia', 'Bastia', 'Bastia', 1),
('Bayonne', 'Nouvelle-Aquitaine', 'Bayonne', 'Pau', 'Bayonne', 1),
('Beauvais', 'Hauts-de-France', 'Beauvais', 'Amiens', 'Beauvais', 1),
('Belfort', 'Bourgogne-Franche-ComtÃ©', 'Belfort', 'BesanÃ§on', 'Belfort', 1),
('Bergerac', 'Nouvelle-Aquitaine', 'Bergerac', 'Bordeaux', 'Bergerac', 1),
('BesanÃ§on', 'Bourgogne-Franche-ComtÃ©', 'BesanÃ§on', 'BesanÃ§on', 'BesanÃ§on', 1),
('BÃ©thune', 'Hauts-de-France', 'BÃ©thune', 'Douai', 'BÃ©thune', 1),
('BÃ©ziers', 'Occitanie', 'BÃ©ziers', 'Montpellier', 'BÃ©ziers', 1),
('Blois', 'Centre-Val de Loire', 'Blois', 'OrlÃ©ans', 'Blois', 1),
('Bobigny', 'ÃŽle-de-France', 'Bobigny', 'Paris', 'Bobigny', 1),
('Bordeaux', 'Nouvelle-Aquitaine', 'Bordeaux', 'Bordeaux', 'Bordeaux', 1),
('Boulogne-sur-Mer', 'Hauts-de-France', 'Boulogne-sur-Mer', 'Douai', 'Boulogne-sur-Mer', 1),
('Bourg-en-Bresse', 'Auvergne-RhÃ´ne-Alpes', 'Bourg-en-Bresse', 'Lyon', 'Bourg-en-Bresse', 1),
('Bourges', 'Centre-Val de Loire', 'Bourges', 'Bourges', 'Bourges', 1),
('Brest', 'Bretagne', 'Brest', 'Rennes', 'Brest', 1),
('Briey', 'Grand Est', 'Briey', 'Nancy', 'Briey', 1),
('Brive-la-Gaillarde', 'Nouvelle-Aquitaine', 'Brive-la-Gaillarde', 'Limoges', 'Brive-la-Gaillarde', 1),
('Caen', 'Normandie', 'Caen', 'Caen', 'Caen', 1),
('Cahors', 'Occitanie', 'Cahors', 'Agen', 'Cahors', 1),
('Cambrai', 'Hauts-de-France', 'Cambrai', 'Douai', 'Cambrai', 1),
('Carcassonne', 'Occitanie', 'Carcassonne', 'Montpellier', 'Carcassonne', 1),
('Carpentras', 'Provence-Alpes-CÃ´te d''Azur', 'Carpentras', 'NÃ®mes', 'Carpentras', 1),
('Castres', 'Occitanie', 'Castres', 'Toulouse', 'Castres', 1),
('Chalon-sur-SaÃ´ne', 'Bourgogne-Franche-ComtÃ©', 'Chalon-sur-SaÃ´ne', 'Dijon', 'Chalon-sur-SaÃ´ne', 1),
('ChÃ¢lons-en-Champagne', 'Grand Est', 'ChÃ¢lons-en-Champagne', 'Reims', 'ChÃ¢lons-en-Champagne', 1),
('ChambÃ©ry', 'Auvergne-RhÃ´ne-Alpes', 'ChambÃ©ry', 'ChambÃ©ry', 'ChambÃ©ry', 1),
('Chartres', 'Centre-Val de Loire', 'Chartres', 'Versailles', 'Chartres', 1),
('Chaumont', 'Grand Est', 'Chaumont', 'Dijon', 'Chaumont', 1),
('Cherbourg-en-Cotentin', 'Normandie', 'Cherbourg-en-Cotentin', 'Caen', 'Cherbourg-en-Cotentin', 1),
('Clermont-Ferrand', 'Auvergne-RhÃ´ne-Alpes', 'Clermont-Ferrand', 'Riom', 'Clermont-Ferrand', 1),
('Colmar', 'Grand Est', 'Colmar', 'Colmar', 'Colmar', 1),
('CompiÃ¨gne', 'Hauts-de-France', 'CompiÃ¨gne', 'Amiens', 'CompiÃ¨gne', 1),
('Coutances', 'Normandie', 'Coutances', 'Caen', 'Coutances', 1),
('CrÃ©teil', 'ÃŽle-de-France', 'CrÃ©teil', 'Paris', 'CrÃ©teil', 1),
('Cusset-Vichy', 'Auvergne-RhÃ´ne-Alpes', 'Cusset', 'Riom', 'Cusset', 1),
('Dax', 'Nouvelle-Aquitaine', 'Dax', 'Pau', 'Dax', 1),
('Dieppe', 'Normandie', 'Dieppe', 'Rouen', 'Dieppe', 1),
('Dijon', 'Bourgogne-Franche-ComtÃ©', 'Dijon', 'Dijon', 'Dijon', 1),
('Douai', 'Hauts-de-France', 'Douai', 'Douai', 'Douai', 1),
('Draguignan', 'Provence-Alpes-CÃ´te d''Azur', 'Draguignan', 'Aix-en-Provence', 'Draguignan', 1),
('Dunkerque', 'Hauts-de-France', 'Dunkerque', 'Douai', 'Dunkerque', 1),
('Ã‰pinal', 'Grand Est', 'Ã‰pinal', 'Nancy', 'Ã‰pinal', 1),
('Essonne', 'ÃŽle-de-France', 'Ã‰vry', 'Paris', 'Ã‰vry', 1),
('Ã‰vreux', 'Normandie', 'Ã‰vreux', 'Rouen', 'Ã‰vreux', 1),
('Foix', 'Occitanie', 'Foix', 'Toulouse', 'Foix', 1),
('Fontainebleau', 'ÃŽle-de-France', 'Fontainebleau', 'Paris', 'Fontainebleau', 1),
('Gap', 'Provence-Alpes-CÃ´te d''Azur', 'Gap', 'Grenoble', 'Gap', 1),
('Grasse', 'Provence-Alpes-CÃ´te d''Azur', 'Grasse', 'Aix-en-Provence', 'Grasse', 1),
('Grenoble', 'Auvergne-RhÃ´ne-Alpes', 'Grenoble', 'Grenoble', 'Grenoble', 1),
('GuÃ©ret', 'Nouvelle-Aquitaine', 'GuÃ©ret', 'Limoges', 'GuÃ©ret', 1),
('Hauts-de-Seine', 'ÃŽle-de-France', 'Nanterre', 'Versailles', 'Nanterre', 1),
('La Rochelle', 'Nouvelle-Aquitaine', 'La Rochelle', 'Poitiers', 'La Rochelle', 1),
('La Roche-sur-Yon', 'Pays de la Loire', 'La Roche-sur-Yon', 'Poitiers', 'La Roche-sur-Yon', 1),
('Laon', 'Hauts-de-France', 'Laon', 'Amiens', 'Laon', 1),
('Laval', 'Pays de la Loire', 'Laval', 'Angers', 'Laval', 1),
('Le Havre', 'Normandie', 'Le Havre', 'Rouen', 'Le Havre', 1),
('Le Mans', 'Pays de la Loire', 'Le Mans', 'Angers', 'Le Mans', 1),
('Le Puy-en-Velay', 'Auvergne-RhÃ´ne-Alpes', 'Le Puy-en-Velay', 'Riom', 'Le Puy-en-Velay', 1),
('Libourne', 'Nouvelle-Aquitaine', 'Libourne', 'Bordeaux', 'Libourne', 1),
('Lille', 'Hauts-de-France', 'Lille', 'Douai', 'Lille', 1),
('Limoges', 'Nouvelle-Aquitaine', 'Limoges', 'Limoges', 'Limoges', 1),
('Lisieux', 'Normandie', 'Lisieux', 'Caen', 'Lisieux', 1),
('Lons-le-Saunier', 'Bourgogne-Franche-ComtÃ©', 'Lons-le-Saunier', 'BesanÃ§on', 'Lons-le-Saunier', 1),
('Lorient', 'Bretagne', 'Lorient', 'Rennes', 'Lorient', 1),
('Lyon', 'Auvergne-RhÃ´ne-Alpes', 'Lyon', 'Lyon', 'Lyon', 1),
('MÃ¢con', 'Bourgogne-Franche-ComtÃ©', 'MÃ¢con', 'Dijon', 'MÃ¢con', 1),
('Marseille', 'Provence-Alpes-CÃ´te d''Azur', 'Marseille', 'Aix-en-Provence', 'Marseille', 1),
('Meaux', 'ÃŽle-de-France', 'Meaux', 'Paris', 'Meaux', 1),
('Melun', 'ÃŽle-de-France', 'Melun', 'Paris', 'Melun', 1),
('Metz', 'Grand Est', 'Metz', 'Metz', 'Metz', 1),
('Montauban', 'Occitanie', 'Montauban', 'Toulouse', 'Montauban', 1),
('MontbÃ©liard', 'Bourgogne-Franche-ComtÃ©', 'MontbÃ©liard', 'BesanÃ§on', 'MontbÃ©liard', 1),
('Mont-de-Marsan', 'Nouvelle-Aquitaine', 'Mont-de-Marsan', 'Pau', 'Mont-de-Marsan', 1),
('MontluÃ§on', 'Auvergne-RhÃ´ne-Alpes', 'MontluÃ§on', 'Riom', 'MontluÃ§on', 1),
('Montpellier', 'Occitanie', 'Montpellier', 'Montpellier', 'Montpellier', 1),
('Morlaix', 'Bretagne', 'Morlaix', 'Rennes', 'Morlaix', 1),
('Moulins', 'Auvergne-RhÃ´ne-Alpes', 'Moulins', 'Riom', 'Moulins', 1),
('Mulhouse', 'Grand Est', 'Mulhouse', 'Colmar', 'Mulhouse', 1),
('Nancy', 'Grand Est', 'Nancy', 'Nancy', 'Nancy', 1),
('Nantes', 'Pays de la Loire', 'Nantes', 'Rennes', 'Nantes', 1),
('Narbonne', 'Occitanie', 'Narbonne', 'Montpellier', 'Narbonne', 1),
('Nevers', 'Bourgogne-Franche-ComtÃ©', 'Nevers', 'Bourges', 'Nevers', 1),
('Nice', 'Provence-Alpes-CÃ´te d''Azur', 'Nice', 'Aix-en-Provence', 'Nice', 1),
('NÃ®mes', 'Occitanie', 'NÃ®mes', 'NÃ®mes', 'NÃ®mes', 1),
('Niort', 'Nouvelle-Aquitaine', 'Niort', 'Poitiers', 'Niort', 1),
('OrlÃ©ans', 'Centre-Val de Loire', 'OrlÃ©ans', 'OrlÃ©ans', 'OrlÃ©ans', 1),
('Paris', 'ÃŽle-de-France', 'Paris', 'Paris', 'Paris', 1),
('Pau', 'Nouvelle-Aquitaine', 'Pau', 'Pau', 'Pau', 1),
('PÃ©rigueux', 'Nouvelle-Aquitaine', 'PÃ©rigueux', 'Bordeaux', 'PÃ©rigueux', 1),
('Perpignan', 'Occitanie', 'Perpignan', 'Montpellier', 'Perpignan', 1),
('Pointe-Ã -Pitre', 'Guadeloupe', 'Pointe-Ã -Pitre', 'Basse-Terre', 'Pointe-Ã -Pitre', 1),
('Poitiers', 'Nouvelle-Aquitaine', 'Poitiers', 'Poitiers', 'Poitiers', 1),
('Pontoise', 'ÃŽle-de-France', 'Pontoise', 'Versailles', 'Pontoise', 1),
('Quimper', 'Bretagne', 'Quimper', 'Rennes', 'Quimper', 1),
('Reims', 'Grand Est', 'Reims', 'Reims', 'Reims', 1),
('Rennes', 'Bretagne', 'Rennes', 'Rennes', 'Rennes', 1),
('Roanne', 'Auvergne-RhÃ´ne-Alpes', 'Roanne', 'Lyon', 'Roanne', 1),
('Rodez', 'Occitanie', 'Rodez', 'Montpellier', 'Rodez', 1),
('Rouen', 'Normandie', 'Rouen', 'Rouen', 'Rouen', 1),
('Saintes', 'Nouvelle-Aquitaine', 'Saintes', 'Poitiers', 'Saintes', 1),
('Saint-Brieuc', 'Bretagne', 'Saint-Brieuc', 'Rennes', 'Saint-Brieuc', 1),
('Saint-Denis de la RÃ©union', 'La RÃ©union', 'Saint-Denis', 'Saint-Denis', 'Saint-Denis', 1),
('Saint-Ã‰tienne', 'Auvergne-RhÃ´ne-Alpes', 'Saint-Ã‰tienne', 'Lyon', 'Saint-Ã‰tienne', 1),
('Saint-Malo', 'Bretagne', 'Saint-Malo', 'Rennes', 'Saint-Malo', 1),
('Saint-Nazaire', 'Pays de la Loire', 'Saint-Nazaire', 'Rennes', 'Saint-Nazaire', 1),
('Saint-Omer', 'Hauts-de-France', 'Saint-Omer', 'Douai', 'Saint-Omer', 1),
('Saint-Pierre de la Martinique', 'Martinique', 'Fort-de-France', 'Fort-de-France', 'Fort-de-France', 1),
('Saint-Quentin', 'Hauts-de-France', 'Saint-Quentin', 'Amiens', 'Saint-Quentin', 1),
('Sarreguemines', 'Grand Est', 'Sarreguemines', 'Metz', 'Sarreguemines', 1),
('Saverne', 'Grand Est', 'Saverne', 'Colmar', 'Saverne', 1),
('Sedan', 'Grand Est', 'Sedan', 'Reims', 'Sedan', 1),
('Senlis', 'Hauts-de-France', 'Senlis', 'Amiens', 'Senlis', 1),
('Sens', 'Bourgogne-Franche-ComtÃ©', 'Sens', 'Paris', 'Sens', 1),
('Soissons', 'Hauts-de-France', 'Soissons', 'Amiens', 'Soissons', 1),
('Strasbourg', 'Grand Est', 'Strasbourg', 'Colmar', 'Strasbourg', 1),
('Tarbes', 'Occitanie', 'Tarbes', 'Pau', 'Tarbes', 1),
('Thionville', 'Grand Est', 'Thionville', 'Metz', 'Thionville', 1),
('Thonon-les-Bains', 'Auvergne-RhÃ´ne-Alpes', 'Thonon-les-Bains', 'ChambÃ©ry', 'Thonon-les-Bains', 1),
('Toulon', 'Provence-Alpes-CÃ´te d''Azur', 'Toulon', 'Aix-en-Provence', 'Toulon', 1),
('Toulouse', 'Occitanie', 'Toulouse', 'Toulouse', 'Toulouse', 1),
('Tours', 'Centre-Val de Loire', 'Tours', 'OrlÃ©ans', 'Tours', 1),
('Troyes', 'Grand Est', 'Troyes', 'Reims', 'Troyes', 1),
('Tulle', 'Nouvelle-Aquitaine', 'Tulle', 'Limoges', 'Tulle', 1),
('Val-de-Briey', 'Grand Est', 'Val-de-Briey', 'Nancy', 'Val-de-Briey', 1),
('Valenciennes', 'Hauts-de-France', 'Valenciennes', 'Douai', 'Valenciennes', 1),
('Vannes', 'Bretagne', 'Vannes', 'Rennes', 'Vannes', 1),
('Verdun', 'Grand Est', 'Verdun', 'Nancy', 'Verdun', 1),
('Versailles', 'ÃŽle-de-France', 'Versailles', 'Versailles', 'Versailles', 1),
('Vesoul', 'Bourgogne-Franche-ComtÃ©', 'Vesoul', 'BesanÃ§on', 'Vesoul', 1),
('Vienne', 'Auvergne-RhÃ´ne-Alpes', 'Vienne', 'Grenoble', 'Vienne', 1),
('Villefranche-sur-SaÃ´ne', 'Auvergne-RhÃ´ne-Alpes', 'Villefranche-sur-SaÃ´ne', 'Lyon', 'Villefranche-sur-SaÃ´ne', 1),
('Cayenne', 'Guyane', 'Cayenne', 'Cayenne', 'Cayenne', 1),
('Mamoudzou', 'Mayotte', 'Mamoudzou', 'Saint-Denis', 'Mamoudzou', 1),
('NoumÃ©a', 'Nouvelle-CalÃ©donie', 'NoumÃ©a', 'NoumÃ©a', 'NoumÃ©a', 1),
('Papeete', 'PolynÃ©sie franÃ§aise', 'Papeete', 'Papeete', 'Papeete', 1);
