INSERT INTO barreaux_france (
  actif, barreau, cour_appel, cour_appel_metropolitaine, nombre_avocats, region, tribunal_judiciaire, ville_siege
) VALUES
(1, 'Agen', 'Agen', NULL, NULL, 'Nouvelle-Aquitaine', 'Tribunal judiciaire de Agen', 'Agen'),
(1, 'Ain', 'Lyon', NULL, NULL, 'Auvergne-Rhône-Alpes', 'Tribunal judiciaire de Bourg-En-Bresse', 'Bourg-En-Bresse'),
(1, 'Aix-en-Provence', 'Aix-en-Provence', NULL, NULL, 'Provence-Alpes-Côte d''Azur', 'Tribunal judiciaire de Aix-En-Provence', 'Aix-En-Provence'),
(1, 'Ajaccio', 'Bastia', NULL, NULL, 'Corse', 'Tribunal judiciaire de Ajaccio', 'Ajaccio'),
(1, 'Albertville', 'Chambéry', NULL, NULL, 'Auvergne-Rhône-Alpes', 'Tribunal judiciaire de Albertville', 'Albertville'),
(1, 'Albi', 'Toulouse', NULL, NULL, 'Occitanie', 'Tribunal judiciaire de Albi', 'Albi'),
(1, 'Alençon', 'Caen', NULL, NULL, 'Normandie', 'Tribunal judiciaire de Alencon', 'Alençon'),
(1, 'Alès', 'Nîmes', NULL, NULL, 'Occitanie', 'Tribunal judiciaire de Al', 'Alès'),
(1, 'Alpes-de-Haute-Provence', 'Aix-en-Provence', NULL, NULL, 'Provence-Alpes-Côte d''Azur', 'Tribunal judiciaire de Digne-Les-Bains', 'Digne-Les-Bains'),
(1, 'Amiens', 'Amiens', NULL, NULL, 'Hauts-de-France', 'Tribunal judiciaire de Amiens', 'Amiens'),
(1, 'Angers', 'Angers', NULL, NULL, 'Pays de la Loire', 'Tribunal judiciaire de Angers', 'Angers'),
(1, 'Annecy', 'Chambéry', NULL, NULL, 'Auvergne-Rhône-Alpes', 'Tribunal judiciaire de Annecy', 'Annecy'),
(1, 'Ardèche', 'Nîmes', NULL, NULL, 'Auvergne-Rhône-Alpes', 'Tribunal judiciaire de Privas', 'Privas'),
(1, 'Ardennes', 'Reims', NULL, NULL, 'Grand Est', 'Tribunal judiciaire de Charleville-M', 'Charleville-M'),
(1, 'Argentan', 'Caen', NULL, NULL, 'Normandie', 'Tribunal judiciaire de Argentan', 'Argentan'),
(1, 'Ariège', 'Toulouse', NULL, NULL, 'Occitanie', 'Tribunal judiciaire de Foix', 'Foix'),
(1, 'Arras', 'Douai', NULL, NULL, 'Hauts-de-France', 'Tribunal judiciaire de Arras', 'Arras'),
(1, 'Aube', 'Reims', NULL, NULL, 'Grand Est', 'Tribunal judiciaire de Troyes', 'Troyes'),
(1, 'Aurillac', 'Riom', NULL, NULL, 'Auvergne-Rhône-Alpes', 'Tribunal judiciaire de Aurillac', 'Aurillac'),
(1, 'Auxerre', 'Paris', NULL, NULL, 'Bourgogne-Franche-Comté', 'Tribunal judiciaire de Auxerre', 'Auxerre'),
(1, 'Avesnes-sur-Helpe', 'Douai', NULL, NULL, 'Hauts-de-France', 'Tribunal judiciaire de Avesnes-Sur-Helpe', 'Avesnes-sur-Helpe'),
(1, 'Aveyron', 'Montpellier', NULL, NULL, 'Occitanie', 'Tribunal judiciaire de Rodez', 'Rodez'),
(1, 'Avignon', 'Nîmes', NULL, NULL, 'Provence-Alpes-Côte d''Azur', 'Tribunal judiciaire de Avignon', 'Avignon'),
(1, 'Bastia', 'Bastia', NULL, NULL, 'Corse', 'Tribunal judiciaire de Bastia', 'Bastia'),
(1, 'Bayonne', 'Pau', NULL, NULL, 'Nouvelle-Aquitaine', 'Tribunal judiciaire de Bayonne', 'Bayonne'),
(1, 'Beauvais', 'Amiens', NULL, NULL, 'Hauts-de-France', 'Tribunal judiciaire de Beauvais', 'Beauvais'),
(1, 'Belfort', 'Besançon', NULL, NULL, 'Bourgogne-Franche-Comté', 'Tribunal judiciaire de Belfort', 'Belfort'),
(1, 'Bergerac', 'Bordeaux', NULL, NULL, 'Nouvelle-Aquitaine', 'Tribunal judiciaire de Bergerac', 'Bergerac'),
(1, 'Besançon', 'Besançon', NULL, NULL, 'Bourgogne-Franche-Comté', 'Tribunal judiciaire de Besançon', 'Besançon'),
(1, 'Béthune', 'Douai', NULL, NULL, 'Hauts-de-France', 'Tribunal judiciaire de Béthune', 'Béthune'),
(1, 'Béziers', 'Montpellier', NULL, NULL, 'Occitanie', 'Tribunal judiciaire de Béziers', 'Béziers'),
(1, 'Blois', 'Orléans', NULL, NULL, 'Centre-Val de Loire', 'Tribunal judiciaire de Blois', 'Blois'),
(1, 'Bonneville et Pays du Mont-Blanc', 'Chambéry', NULL, NULL, 'Auvergne-Rhône-Alpes', 'Tribunal judiciaire de Bonneville', 'Bonneville'),
(1, 'Bordeaux', 'Bordeaux', NULL, NULL, 'Nouvelle-Aquitaine', 'Tribunal judiciaire de Bordeaux', 'Bordeaux'),
(1, 'Boulogne-sur-Mer', 'Douai', NULL, NULL, 'Hauts-de-France', 'Tribunal judiciaire de Boulogne-Sur-Mer', 'Boulogne-sur-Mer'),
(1, 'Bourges', 'Bourges', NULL, NULL, 'Centre-Val de Loire', 'Tribunal judiciaire de Bourges', 'Bourges'),
(1, 'Bourgoin-Jallieu', 'Grenoble', NULL, NULL, 'Auvergne-Rhône-Alpes', 'Tribunal judiciaire de Bourgoin-Jallieu', 'Bourgoin-Jallieu'),
(1, 'Brest', 'Rennes', NULL, NULL, 'Bretagne', 'Tribunal judiciaire de Brest', 'Brest'),
(1, 'Briey', 'Nancy', NULL, NULL, 'Grand Est', 'Tribunal judiciaire de Val-De-Briey', 'Val-De-Briey'),
(1, 'Brive-la-Gaillarde', 'Limoges', NULL, NULL, 'Nouvelle-Aquitaine', 'Tribunal judiciaire de Brive-La-Gaillarde', 'Brive-La-Gaillarde'),
(1, 'Caen', 'Caen', NULL, NULL, 'Normandie', 'Tribunal judiciaire de Caen', 'Caen'),
(1, 'Cambrai', 'Douai', NULL, NULL, 'Hauts-de-France', 'Tribunal judiciaire de Cambrai', 'Cambrai'),
(1, 'Carcassonne', 'Montpellier', NULL, NULL, 'Occitanie', 'Tribunal judiciaire de Carcassonne', 'Carcassonne'),
(1, 'Carpentras', 'Nîmes', NULL, NULL, 'Provence-Alpes-Côte d''Azur', 'Tribunal judiciaire de Carpentras', 'Carpentras'),
(1, 'Castres', 'Toulouse', NULL, NULL, 'Occitanie', 'Tribunal judiciaire de Castres', 'Castres'),
(1, 'Chalon-sur-Saône', 'Dijon', NULL, NULL, 'Grand Est', 'Tribunal judiciaire de Chalon-Sur-Saône', 'Chalon-sur-Saône'),
(1, 'Chalons-en-Champagne', 'Reims', NULL, NULL, 'Bourgogne-Franche-Comté', 'Tribunal judiciaire de Chalons-En-Champagne', 'Chalons-en-Champagne'),
(1, 'Chambéry', 'Chambéry', NULL, NULL, 'Auvergne-Rhône-Alpes', 'Tribunal judiciaire de Chambéry', 'Chambéry'),
(1, 'Charente', 'Bordeaux', NULL, NULL, 'Nouvelle-Aquitaine', 'Tribunal judiciaire de Angouleme', 'Angouleme'),
(1, 'Chartres', 'Versailles', NULL, NULL, 'Centre-Val de Loire', 'Tribunal judiciaire de Chartres', 'Chartres'),
(1, 'Châteauroux', 'Bourges', NULL, NULL, 'Centre-Val de Loire', 'Tribunal judiciaire de Châteauroux', 'Châteauroux'),
(1, 'Cherbourg', 'Caen', NULL, NULL, 'Normandie', 'Tribunal judiciaire de Cherbourg', 'Cherbourg'),
(1, 'Clermont-Ferrand', 'Riom', NULL, NULL, 'Auvergne-Rhône-Alpes', 'Tribunal judiciaire de Clermont-Ferrand', 'Clermont-Ferrand'),
(1, 'Colmar', 'Colmar', NULL, NULL, 'Grand Est', 'Tribunal judiciaire de Colmar', 'Colmar'),
(1, 'Compiègne', 'Amiens', NULL, NULL, 'Hauts-de-France', 'Tribunal judiciaire de Compiègne', 'Compiègne'),
(1, 'Coutances', 'Caen', NULL, NULL, 'Normandie', 'Tribunal judiciaire de Coutances', 'Coutances'),
(1, 'Creuse', 'Limoges', NULL, NULL, 'Nouvelle-Aquitaine', 'Tribunal judiciaire de Gueret', 'Gueret'),
(1, 'Cusset-Vichy', 'Riom', NULL, NULL, 'Auvergne-Rhône-Alpes', 'Tribunal judiciaire de Cusset', 'Cusset'),
(1, 'Dax', 'Pau', NULL, NULL, 'Nouvelle-Aquitaine', 'Tribunal judiciaire de Dax', 'Dax'),
(1, 'Deux-Sèvres', 'Poitiers', NULL, NULL, 'Nouvelle-Aquitaine', 'Tribunal judiciaire de Niort', 'Niort'),
(1, 'Dieppe', 'Rouen', NULL, NULL, 'Normandie', 'Tribunal judiciaire de Dieppe', 'Dieppe'),
(1, 'Dijon', 'Dijon', NULL, NULL, 'Bourgogne-Franche-Comté', 'Tribunal judiciaire de Dijon', 'Dijon'),
(1, 'Douai', 'Douai', NULL, NULL, 'Hauts-de-France', 'Tribunal judiciaire de Douai', 'Douai'),
(1, 'Draguignan', 'Aix-en-Provence', NULL, NULL, 'Provence-Alpes-Côte d''Azur', 'Tribunal judiciaire de Draguignan', 'Draguignan'),
(1, 'Drôme', 'Grenoble', NULL, NULL, 'Auvergne-Rhône-Alpes', 'Tribunal judiciaire de Valence', 'Valence'),
(1, 'Dunkerque', 'Douai', NULL, NULL, 'Hauts-de-France', 'Tribunal judiciaire de Dunkerque', 'Dunkerque'),
(1, 'Épinal', 'Nancy', NULL, NULL, 'Grand Est', 'Tribunal judiciaire de Épinal', 'Épinal'),
(1, 'Essonne', 'Paris', NULL, NULL, 'Île-de-France', 'Tribunal judiciaire de Évry', 'Évry'),
(1, 'Eure', 'Rouen', NULL, NULL, 'Normandie', 'Tribunal judiciaire de Évreux', 'Évreux'),
(1, 'Fontainebleau', 'Paris', NULL, NULL, 'Île-de-France', 'Tribunal judiciaire de Fontainebleau', 'Fontainebleau'),
(1, 'Gers', 'Agen', NULL, NULL, 'Occitanie', 'Tribunal judiciaire de Auch', 'Auch'),
(1, 'Grasse', 'Aix-en-Provence', NULL, NULL, 'Provence-Alpes-Côte d''Azur', 'Tribunal judiciaire de Grasse', 'Grasse'),
(1, 'Grenoble', 'Grenoble', NULL, NULL, 'Auvergne-Rhône-Alpes', 'Tribunal judiciaire de Grenoble', 'Grenoble'),
(1, 'Guadeloupe', 'Basse-Terre', NULL, NULL, 'Guadeloupe', 'Tribunal judiciaire de Basse-Terre', 'Basse-Terre'),
(1, 'Guyane', 'Cayenne', NULL, NULL, 'Guyane', 'Tribunal judiciaire de Cayenne', 'Cayenne'),
(1, 'Haute-Loire', 'Riom', NULL, NULL, 'Auvergne-Rhône-Alpes', 'Tribunal judiciaire de Le-Puy-En-Velay', 'Le-Puy-En-Velay'),
(1, 'Haute-Marne', 'Dijon', NULL, NULL, 'Grand Est', 'Tribunal judiciaire de Chaumont', 'Chaumont'),
(1, 'Haute-Saône-Vesoul', 'Besançon', NULL, NULL, 'Bourgogne-Franche-Comté', 'Tribunal judiciaire de Vesoul', 'Vesoul'),
(1, 'Hautes-Alpes', 'Grenoble', NULL, NULL, 'Provence-Alpes-Côte d''Azur', 'Tribunal judiciaire de Gap', 'Gap'),
(1, 'Hauts-de-Seine', 'Versailles', NULL, NULL, 'Île-de-France', 'Tribunal judiciaire de Nanterre', 'Nanterre'),
(1, 'Jura', 'Besançon', NULL, NULL, 'Bourgogne-Franche-Comté', 'Tribunal judiciaire de Lons-Le-Saunier', 'Lons-Le-Saunier'),
(1, 'La Rochelle', 'Poitiers', NULL, NULL, 'Nouvelle-Aquitaine', 'Tribunal judiciaire de La Rochelle', 'La Rochelle'),
(1, 'La-Roche-sur-Yon', 'Poitiers', NULL, NULL, 'Pays de la Loire', 'Tribunal judiciaire de La-Roche-Sur-Yon', 'La-Roche-Sur-Yon'),
(1, 'Laon', 'Amiens', NULL, NULL, 'Hauts-de-France', 'Tribunal judiciaire de Laon', 'Laon'),
(1, 'Laval', 'Laval', NULL, NULL, 'Pays de la Loire', 'Tribunal judiciaire de Laval', 'Laval'),
(1, 'Le Havre', 'Rouen', NULL, NULL, 'Normandie', 'Tribunal judiciaire de Le Havre', 'Le Havre'),
(1, 'Le Mans', 'Angers', NULL, NULL, 'Pays de la Loire', 'Tribunal judiciaire de Le Mans', 'Le Mans'),
(1, 'Libourne', 'Bordeaux', NULL, NULL, 'Nouvelle-Aquitaine', 'Tribunal judiciaire de Libourne', 'Libourne'),
(1, 'Lille', 'Douai', NULL, NULL, 'Hauts-de-France', 'Tribunal judiciaire de Lille', 'Lille'),
(1, 'Limoges', 'Limoges', NULL, NULL, 'Nouvelle-Aquitaine', 'Tribunal judiciaire de Limoges', 'Limoges'),
(1, 'Lisieux', 'Caen', NULL, NULL, 'Normandie', 'Tribunal judiciaire de Lisieux', 'Lisieux'),
(1, 'Lorient', 'Rennes', NULL, NULL, 'Bretagne', 'Tribunal judiciaire de Lorient', 'Lorient'),
(1, 'Lot', 'Agen', NULL, NULL, 'Occitanie', 'Tribunal judiciaire de Cahors', 'Cahors'),
(1, 'Lozère', 'Rennes', NULL, NULL, 'Occitanie', 'Tribunal judiciaire de Mende', 'Mende'),
(1, 'Lyon', 'Lyon', NULL, NULL, 'Auvergne-Rhône-Alpes', 'Tribunal judiciaire de Lyon', 'Lyon'),
(1, 'Mâcon-Charolles', 'Dijon', NULL, NULL, 'Bourgogne-Franche-Comté', 'Tribunal judiciaire de Mâcon', 'Mâcon'),
(1, 'Marseille', 'Aix-en-Provence', NULL, NULL, 'Provence-Alpes-Côte d''Azur', 'Tribunal judiciaire de Marseille', 'Marseille'),
(1, 'Martinique', 'Fort-de-France', NULL, NULL, 'Martinique', 'Tribunal judiciaire de Fort-De-France', 'Fort-De-France'),
(1, 'Mayotte', 'Saint-Denis', NULL, NULL, 'Mayotte', 'Tribunal judiciaire de Mamoudzou', 'Mamoudzou'),
(1, 'Meaux', 'Paris', NULL, NULL, 'Île-de-France', 'Tribunal judiciaire de Meaux', 'Meaux'),
(1, 'Melun', 'Paris', NULL, NULL, 'Île-de-France', 'Tribunal judiciaire de Melun', 'Melun'),
(1, 'Metz', 'Metz', NULL, NULL, 'Grand Est', 'Tribunal judiciaire de Metz', 'Metz'),
(1, 'Meuse', 'Nancy', NULL, NULL, 'Grand Est', 'Tribunal judiciaire de Bar-Le-Duc', 'Bar-Le-Duc'),
(1, 'Mont-de-Marsan', 'Pau', NULL, NULL, 'Nouvelle-Aquitaine', 'Tribunal judiciaire de Mont-De-Marsan', 'Mont-De-Marsan'),
(1, 'Montargis', 'Orléans', NULL, NULL, 'Centre-Val de Loire', 'Tribunal judiciaire de Montargis', 'Montargis'),
(1, 'Montbéliard', 'Besançon', NULL, NULL, 'Bourgogne-Franche-Comté', 'Tribunal judiciaire de Montbéliard', 'Montbéliard'),
(1, 'Montluçon', 'Riom', NULL, NULL, 'Auvergne-Rhône-Alpes', 'Tribunal judiciaire de Montluçon', 'Montluçon'),
(1, 'Montpellier', 'Montpellier', NULL, NULL, 'Occitanie', 'Tribunal judiciaire de Montpellier', 'Montpellier'),
(1, 'Moulins', 'Riom', NULL, NULL, 'Auvergne-Rhône-Alpes', 'Tribunal judiciaire de Moulins', 'Moulins'),
(1, 'Mulhouse', 'Colmar', NULL, NULL, 'Grand Est', 'Tribunal judiciaire de Mulhouse', 'Mulhouse'),
(1, 'Nancy', 'Nancy', NULL, NULL, 'Grand Est', 'Tribunal judiciaire de Nancy', 'Nancy'),
(1, 'Nantes', 'Rennes', NULL, NULL, 'Pays de la Loire', 'Tribunal judiciaire de Nantes', 'Nantes'),
(1, 'Narbonne', 'Montpellier', NULL, NULL, 'Occitanie', 'Tribunal judiciaire de Narbonne', 'Narbonne'),
(1, 'Nevers', 'Bourges', NULL, NULL, 'Bourgogne-Franche-Comté', 'Tribunal judiciaire de Nevers', 'Nevers'),
(1, 'Nice', 'Aix-en-Provence', NULL, NULL, 'Provence-Alpes-Côte d''Azur', 'Tribunal judiciaire de Nice', 'Nice'),
(1, 'Nîmes', 'Nîmes', NULL, NULL, 'Occitanie', 'Tribunal judiciaire de Nîmes', 'Nîmes'),
(1, 'Nouméa', NULL, NULL, NULL, 'Nouvelle-Calédonie', 'Tribunal judiciaire de Nouméa', 'Nouméa'),
(1, 'Orléans', 'Orléans', NULL, NULL, 'Centre-Val de Loire', 'Tribunal judiciaire de Orléans', 'Orléans'),
(1, 'Papeete', NULL, NULL, NULL, 'Polynésie française', 'Tribunal judiciaire de Papeete', 'Papeete'),
(1, 'Paris', 'Paris', NULL, NULL, 'Île-de-France', 'Tribunal judiciaire de Paris', 'Paris'),
(1, 'Pau', 'Pau', NULL, NULL, 'Nouvelle-Aquitaine', 'Tribunal judiciaire de Pau', 'Pau'),
(1, 'Périgueux', 'Bordeaux', NULL, NULL, 'Nouvelle-Aquitaine', 'Tribunal judiciaire de Périgueux', 'Périgueux'),
(1, 'Poitiers', 'Poitiers', NULL, NULL, 'Nouvelle-Aquitaine', 'Tribunal judiciaire de Poitiers', 'Poitiers'),
(1, 'Pyrénées-Orientales', 'Montpellier', NULL, NULL, 'Occitanie', 'Tribunal judiciaire de Perpignan', 'Perpignan'),
(1, 'Quimper', 'Rennes', NULL, NULL, 'Bretagne', 'Tribunal judiciaire de Quimper', 'Quimper'),
(1, 'Reims', 'Reims', NULL, NULL, 'Grand Est', 'Tribunal judiciaire de Reims', 'Reims'),
(1, 'Rennes', 'Rennes', NULL, NULL, 'Bretagne', 'Tribunal judiciaire de Rennes', 'Rennes'),
(1, 'Roanne', 'Lyon', NULL, NULL, 'Auvergne-Rhône-Alpes', 'Tribunal judiciaire de Roanne', 'Roanne'),
(1, 'Rouen', 'Rouen', NULL, NULL, 'Normandie', 'Tribunal judiciaire de Rouen', 'Rouen'),
(1, 'Sables-d''Olonne', 'Poitiers', NULL, NULL, 'Pays de la Loire', 'Tribunal judiciaire de Les Sables-d''Olonne', 'Les Sables-d''Olonne'),
(1, 'Saint-Brieuc', 'Rennes', NULL, NULL, 'Bretagne', 'Tribunal judiciaire de Saint-Brieuc', 'Saint-Brieuc'),
(1, 'Saint-Denis-La-Réunion', 'Saint-Denis', NULL, NULL, 'La Réunion', 'Tribunal judiciaire de Saint-Denis', 'Saint-Denis'),
(1, 'Saint-Étienne', 'Lyon', NULL, NULL, 'Auvergne-Rhône-Alpes', 'Tribunal judiciaire de Saint-Étienne', 'Saint-Étienne'),
(1, 'Saint-Gaudens', 'Toulouse', NULL, NULL, 'Occitanie', 'Tribunal judiciaire de Saint-Gaudens', 'Saint-Gaudens'),
(1, 'Saint-Malo-Dinan', 'Rennes', NULL, NULL, 'Bretagne', 'Tribunal judiciaire de Saint-Malo', 'Saint-Malo'),
(1, 'Saint-Nazaire', 'Rennes', NULL, NULL, 'Pays de la Loire', 'Tribunal judiciaire de Saint-Nazaire', 'Saint-Nazaire'),
(1, 'Saint-Omer', 'Douai', NULL, NULL, 'Hauts-de-France', 'Tribunal judiciaire de Saint-Omer', 'Saint-Omer'),
(1, 'Saint-Pierre-La-Réunion', 'Saint-Denis', NULL, NULL, 'La Réunion', 'Tribunal judiciaire de Saint-Pierre', 'Saint-Pierre'),
(1, 'Saint-Quentin', 'Amiens', NULL, NULL, 'Hauts-de-France', 'Tribunal judiciaire de Saint-Quentin', 'Saint-Quentin'),
(1, 'Saintes', 'Poitiers', NULL, NULL, 'Nouvelle-Aquitaine', 'Tribunal judiciaire de Saintes', 'Saintes'),
(1, 'Sarreguemines', 'Metz', NULL, NULL, 'Grand Est', 'Tribunal judiciaire de Sarreguemines', 'Sarreguemines'),
(1, 'Saumur', 'Angers', NULL, NULL, 'Pays de la Loire', 'Tribunal judiciaire de Saumur', 'Saumur'),
(1, 'Saverne', 'Colmar', NULL, NULL, 'Grand Est', 'Tribunal judiciaire de Saverne', 'Saverne'),
(1, 'Seine-Saint-Denis', 'Paris', NULL, NULL, 'Île-de-France', 'Tribunal judiciaire de Bobigny', 'Bobigny'),
(1, 'Senlis', 'Amiens', NULL, NULL, 'Hauts-de-France', 'Tribunal judiciaire de Senlis', 'Senlis'),
(1, 'Sens', 'Paris', NULL, NULL, 'Bourgogne-Franche-Comté', 'Tribunal judiciaire de Sens', 'Sens'),
(1, 'Soissons', 'Amiens', NULL, NULL, 'Hauts-de-France', 'Tribunal judiciaire de Soissons', 'Soissons'),
(1, 'Strasbourg', 'Colmar', NULL, NULL, 'Grand Est', 'Tribunal judiciaire de Strasbourg', 'Strasbourg'),
(1, 'Tarascon', 'Aix-en-Provence', NULL, NULL, 'Provence-Alpes-Côte d''Azur', 'Tribunal judiciaire de Tarascon', 'Tarascon'),
(1, 'Tarbes', 'Pau', NULL, NULL, 'Occitanie', 'Tribunal judiciaire de Tarbes', 'Tarbes'),
(1, 'Tarn-et-Garonne', 'Toulouse', NULL, NULL, 'Occitanie', 'Tribunal judiciaire de Montauban', 'Montauban'),
(1, 'Thionville', 'Metz', NULL, NULL, 'Grand Est', 'Tribunal judiciaire de Thionville', 'Thionville'),
(1, 'Thonon-les-Bains, Léman et Genevois', 'Chambéry', NULL, NULL, 'Auvergne-Rhône-Alpes', 'Tribunal judiciaire de Thonon-Les-Bains', 'Thonon-Les-Bains'),
(1, 'Toulon', 'Aix-en-Provence', NULL, NULL, 'Provence-Alpes-Côte d''Azur', 'Tribunal judiciaire de Toulon', 'Toulon'),
(1, 'Toulouse', 'Toulouse', NULL, NULL, 'Occitanie', 'Tribunal judiciaire de Toulouse', 'Toulouse'),
(1, 'Tours', 'Orléans', NULL, NULL, 'Centre-Val de Loire', 'Tribunal judiciaire de Tours', 'Tours'),
(1, 'Tulle', 'Limoges', NULL, NULL, 'Nouvelle-Aquitaine', 'Tribunal judiciaire de Tulle', 'Tulle'),
(1, 'Val-d''Oise', 'Versailles', NULL, NULL, 'Île-de-France', 'Tribunal judiciaire de Pontoise', 'Pontoise'),
(1, 'Val-de-Marne-Créteil', 'Paris', NULL, NULL, 'Île-de-France', 'Tribunal judiciaire de Créteil', 'Créteil'),
(1, 'Valenciennes', 'Douai', NULL, NULL, 'Hauts-de-France', 'Tribunal judiciaire de Valenciennes', 'Valenciennes'),
(1, 'Vannes', 'Rennes', NULL, NULL, 'Bretagne', 'Tribunal judiciaire de Vannes', 'Vannes'),
(1, 'Versailles', 'Versailles', NULL, NULL, 'Île-de-France', 'Tribunal judiciaire de Versailles', 'Versailles'),
(1, 'Vienne', 'Grenoble', NULL, NULL, 'Auvergne-Rhône-Alpes', 'Tribunal judiciaire de Vienne', 'Vienne'),
(1, 'Villefranche-sur-Saône', 'Lyon', NULL, NULL, 'Auvergne-Rhône-Alpes', 'Tribunal judiciaire de Villefranche-Sur-Saône', 'Villefranche-sur-Saône');
